### ISSUE TITLE
这例子写得一脸懵，都不知道怎么配置才行

### ISSUE THREAD

**Issue by yyggg** [xbzbing/Yii2-UEditor#10]

**Comment by xbzbing** [comment]
使用扩展前需要先熟悉Yii2框架本身。
Yii官网地址：https://www.yiiframework.com

扩展由两部分组成：
1. 前台界面
就是从浏览器看到的编辑器，所以这部分配置在view里面。
参考:
https://www.yiiframework.com/doc/guide/2.0/zh-cn/input-forms
https://github.com/xbzbing/Yii2-UEditor#在模板中使用
http://fex.baidu.com/ueditor/#start-config

2. 上传后台
后台负责配置、上传等功能的具体实现。
参考:
https://www.yiiframework.com/doc/guide/2.0/zh-cn/runtime-routing
http://fex.baidu.com/ueditor/#server-deploy
https://github.com/xbzbing/Yii2-UEditor#后端支持
