### ISSUE TITLE
建议增加上传到云存储功能

### ISSUE THREAD

**Issue by ghost** [xbzbing/Yii2-UEditor#2]
比如七牛、又拍、阿里云OSS。
另外如果用水印的话，如果要加到原图的右下角，那两个值应该怎样写？（现在一般来说水印都是加到右下角）

**Comment by xbzbing** [comment]
感谢反馈，发现水印处有 bug，已经修复并发布新版本。

1、云存储原来打算写的，后来写了一个七牛发现代码太简单就放弃了，所以这块请自行扩展。
2、水印之前是承接 Yii1 扩展的方法写的，结果存在几个 bug 没有发现，感谢反馈，现在已经修复。
水印需要设定 wartermark，设置为`$watermark = ['path' => '水印图片的绝对路径', 'position' => 9]`，其中position表示位置，想要放到右下角就写 9，默认是 9。

```
'watermark' => [    //默认不生存水印
                'path' => '', //水印图片路径
                'position' => 9 //position in [1, 9]，表示从左上到右下的 9 个位置，即如1表示左上，5表示中间，9表示右下。
            ],
```

**Comment by ghost** [comment]
@xbzbing 我之前用Laravel的UEditor扩展， 他自带上传到七牛的功能，虽然我可以通过扩展实现，但我担心一composer update之后，我做的修改就没了。

**Comment by xbzbing** [comment]
可以通过继承 UEditorController 来做定制修改，不用修改扩展本身。
好吧，其实是因为我最近比较忙没空搞这个，我看看周末增加下吧。
