### ISSUE TITLE
生成略缩图有问题

### ISSUE THREAD

**Issue by picone** [xbzbing/Yii2-UEditor#4]
生成不了略缩图
解决方法是修改[https://github.com/xbzbing/Yii2-UEditor/blob/master/UEditorController.php#L318](https://github.com/xbzbing/Yii2-UEditor/blob/master/UEditorController.php#L318) 这里的```thumbnail```传过去的第二个参数。第二个参数应该是原图片的路径，而不是略缩图保存的路径，这样会在ensureImageInterfaceInstance时抛出文件不存在的错误。
额，解决一下吧，这样我就不用复制粘贴一大段代码来解决你这个问题了。

**Comment by xbzbing** [comment]
收到，一会我回去看看。

**Comment by xbzbing** [comment]
thx，已经修复。
