### ISSUE TITLE
不支持多个编辑器的name写法

### ISSUE THREAD

**Issue by zhanguangcheng** [xbzbing/Yii2-UEditor#6]
```php
\crazydb\ueditor\UEditor::widget([
      'name' => 'ueditors[one]',
        'value' => $value
]);
```
这样写就会报错,  另外UEditor官方的name配置是textarea参数, 如下设置后不生效: 
```php
 \crazydb\ueditor\UEditor::widget([
        'name' => 'ueditor',
        'value' => $value,
        'config' => [
            'textarea' => 'ueditors[one]'
        ]
 ]);
```

**Comment by xbzbing** [comment]
因为 name 属性会在页面注册 js 作为变量名字存在，所以不能用[]这类的特殊符号。详见代码[UEditor.php](https://github.com/xbzbing/Yii2-UEditor/blob/master/UEditor.php#L133)。

使用 form model 没有问题，普通表单确实有问题，我修复下。

多谢反馈。

**Comment by zhanguangcheng** [comment]
源码已经看了, 我知道是这个原因.  因为HTML的标签的name值这样写是合法的, 我是希望作者能够修复该问题, 让其支持多个编辑器的name值写法.  或者用官方的textarea参数配置作为标签的name值.

**Comment by xbzbing** [comment]
已经修复。去掉了实例，需要自己获取。在普通表单的使用方法中支持 textarea 方法，优先级比 name 属性要高。
