### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by CGA476094464** [xbzbing/Yii2-UEditor#7]
上传时建议加个isset，这样就不会报Undefined index: upfile错误

**Comment by xbzbing** [comment]
请问是什么功能报错的？请把详细日志贴出来我定位下异常位置，谢谢。

**Comment by CGA476094464** [comment]
我是把你的插件做成接口提供给前端调用的。upload-image时，根据ImageFileName获取值，当未选择文件直接访问时FILE会报Undefined index: upfile，加上一个isset然后主动提示错误这样能避免程序报错

**Comment by xbzbing** [comment]
已修复，多谢反馈。
